name: build
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo
        env:
          HUGO_VERSION: 0.74.1
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          ref: docs
          path: docs

      - name: Hugo Build
        run: cd main && hugo 
    
      - name: Where am i
        run: ls

      # - name: Commit to master
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Action"

      #     git add docs

      #     if git diff-index --quiet HEAD --; then
      #       echo "No changes..."
      #     else
      #       git commit -m "[CI] build hugo static site"
      #       git push
      #     fi

